### ISSUE TITLE
请求支持js模块中的中文属性

### ISSUE THREAD

**Issue by lsby** [program-in-chinese/vscode_Chinese_Input_Assistant#18]
## 操作过程

先编写代码
```
var Obj={中文:1}
```
然后在下一行输入
```
Obj.
```
此时弹出了提示,如图所示.
![](https://github.com/lsby/tuchuang1/blob/master/2020%E5%B9%B46%E6%9C%8826%E6%97%A51.png?raw=true)

此时,不按esc,而是继续以英文输入法输入z

## 预期行为
会匹配到"中文"这个属性
示意图:
![](https://github.com/lsby/tuchuang1/blob/master/2020%E5%B9%B46%E6%9C%8826%E6%97%A52.png?raw=true)

## 实际行为
会什么都不发生
![](https://github.com/lsby/tuchuang1/blob/master/2020%E5%B9%B46%E6%9C%8826%E6%97%A53.png?raw=true)

## 可能的解决方法
输入点后,按esc,然后输入z,程序会读取**本文件**的中文关键词.
但如果对象定义在不同文件中,依然无法获取到其中文属性.

## 上下文
这对我很有用,因为我的库中有大量中文属性.
![](https://github.com/lsby/tuchuang1/blob/master/QQ%E6%88%AA%E5%9B%BE20200626132536.png?raw=true)
如果能通过简拼找到对应的属性会很方便

**Comment by nobodxbodon** [comment]
试了一下输入到`zho`或者`zhw`时就出现了`中文`, 猜是不是自动补全机制需要匹配到一定程度...
![Screen Shot 2020-06-25 at 10 44 30 PM](https://user-images.githubusercontent.com/392497/85824836-90e07400-b735-11ea-9d70-70d7bdbe73c4.png)
![Screen Shot 2020-06-25 at 10 46 15 PM](https://user-images.githubusercontent.com/392497/85824881-ad7cac00-b735-11ea-9eb6-bd47343ae437.png)

**Comment by lsby** [comment]
@zj1d 看到了修复,感谢.

**Comment by nobodxbodon** [comment]
@lsby 没明白这个 commit 啥功能。。你测试过了吗？啥效果啊？

**Comment by lsby** [comment]
> @lsby没明白这个commit啥功能。。你测试过了吗？啥效果啊？

就是输入点直接就会看到拼音补全.
我刚才拉分支上的代码在本地调试试了.
